### ISSUE TITLE
Feature request: Bound methods

### ISSUE THREAD

**Issue by bjmiller** [WebReflection/es-class#1]
I'd like to have an easy way to mark specific methods in a class implementation so that every reference to `this` within those methods is bound to the object's actual `this` when processed.  This can be done by wrapping with a function that uses call/apply, using Function#bind, or anything else that works.

If you're amenable to this, I can work on a PR.

**Comment by WebReflection** [comment]
it's already in [eddy](https://github.com/WebReflection/eddy#event-driven-js), it's called `boundTo` and it works lazily so you don't have to overload each instance creation with all bounded methods upfront.

Alternatively, you want a trait/mixin that does magic inside its `init` method.

When anything like this will land natively in ECMAScript though, or other transpilers classic OOP oriented like TypeScript, I'll be more than happpy to implement it.

**Comment by bjmiller** [comment]
OK.  I'll just need to keep a lightweight binding tool around.

The reason I wanted this feature is that it's common in CoffeeScript, and I wanted that available in vanilla JS, as well.  es-class gives me every other feature I wanted for object construction.  So, between that and TypeScript's support of it using arrow expressions, I'd say it's in use among a lot of transpiler-positive programmers.  As for whether ES will ever do something like that, I suspect that won't happen. The TC will likely just say "Use Function#bind".

**Comment by WebReflection** [comment]
uhm, if you use 6to5 with whitelisted method shorthand you can write 
```js
var MyClass = Class({
  myMethod() {
    return this.bla;
  }
});
```
Having everything bound per each created instance is a bit of a no-go for performance, but you can bring in your mixin and decide how, when, and eventually what to bind.

```js
var Boundable = {
  boundTo: function () {
    for (var
      bind = function (self, key) {
        var method = self[key];
        return function () {
          return method.apply(self, arguments);
        }
      },
      i = 0,
      key;
      i < arguments.length;
      i++
    ) {
      bind(this, arguments[i]);
    }
    return this;
  }
};
```
Then per each class you want this ...
```js
var MyClas = Class({
  with: [Boundable],
  constructor: function () {
    this.boundTo('method');
  },
  method: function () {
    return this;
  }
});

var o = new MyClass
o.method() === o;
(o.method).call(null) === o;
```

would something like that work?

**Comment by bjmiller** [comment]
Probably.  I thought about something similar, but now I'm more thinking something like Underscore's `bindAll` function.  So, I can either bind at definition time, or perhaps even right before I use the method.

**Comment by WebReflection** [comment]
I am not sure that's going to work. ES6 defines methods as non enumerable, so does es-class.
AFAICT lodash bindAll uses keysIn and checks hasOwnProperty, you gonna miss also eventually inherited methods.

I personally would go explicit with something similar I've suggested, it won't fail and it does not require dependencies.

Anyway, you know what you need so, pick your weapon and move on ;-)
