### ISSUE TITLE
Feature Request: Deep Merging Statics

### ISSUE THREAD

**Issue by triggity** [WebReflection/es-class#3]
It would be great if the static object can be deep merged instead of shallow. use case is something like React.Component and defaultProps/propTypes. an example modified from your example
```
var Panel = Class({
  extends: React.Component,
  static: {
    propTypes: {
      SCROLLABLE: React.PropTypes.bool
    },
    defaultProps: {
      SCROLLABLE: true
    }
   }
});
var Page = Class({
  extends: Panel,
  static: {
    propTypes: {
      RESIZABLE: React.PropTypes.bool
    },
    defaultProps: {
      RESIZABLE: true
    }
   }
});
```

defaultProps and propTypes are shallow-ly merged. for now, this is work-around-able by manually deep merging in the Page Class definition

**Comment by WebReflection** [comment]
not sure I've got the problem ... so, statics are inherited ... like methods and properties, and as such,  can  be overwritten/redefined.

Is this your issue?

**Comment by triggity** [comment]
what i mean is this:

``` 
> Page.defaultProps
{ RESIZABLE: true }
```

desired: a deep merge on properties if possible so that i get
```
> Page.defaultProps
{ RESIZABLE: true, SCROLLABLE: true }
```

**Comment by WebReflection** [comment]
can we have an example that doesn't use any external library and doesn't fail at syntax please? 'cause I think it's already like you wish, but you have some missing comma there and an external unknown  class that might be a separate issue. Thanks

**Comment by WebReflection** [comment]
actually never mind, I've just realized what is that you are asking. Sorry I couldn't see before the difference. Will look at this, cheers!

**Comment by triggity** [comment]
i edited the original source during my first comment because i saw the syntax error. it should be fine now

**Comment by WebReflection** [comment]
are you planning to do that with inherited data too? (hope not)

**Comment by triggity** [comment]
absolutely not.

**Comment by WebReflection** [comment]
I think it's done in version `2.0.0` which has been pushed already. I've bumped 'cause there are quite few consistent changes but [the new test](https://github.com/WebReflection/es-class/blob/master/test/es-class.js#L715-L757) tells me it should now work as you expect.

Please let me know if that is not the case, or close this FR otherwise, cheers.

**Comment by WebReflection** [comment]
hey @triggity , did you have a chance to confirm we are all good here? Cheers

**Comment by WebReflection** [comment]
![screenshot from 2015-10-01 11-51-38](https://cloud.githubusercontent.com/assets/85749/10217844/d2124e14-6832-11e5-9b05-43f506f4eaa7.png)

**Comment by WebReflection** [comment]
sorry, wrong tab

**Comment by triggity** [comment]
on v2.0.0 this deep merges and has been resolved. thanks!

**Comment by WebReflection** [comment]
glad to know ... meanwhile, because of this, this happened too: https://github.com/WebReflection/cloner

So thanks for the feature request, it has been interesting to solve it.
